/**
 * Official Abuja Church Geographic Coordinate Mapping for CEAZ1 ReachOut Campaign
 * Map canvas space: 1200 x 900
 * Note: All churches in Zonal Church Group are located in Jabi District.
 */

export interface ChurchMapLocation {
  id: string;
  groupId: string;
  groupName: string;
  name: string;
  code: string;
  districtKey: string;
  districtName: string;
  region: string;
  x: number;
  y: number;
  isZonalHQ: boolean;
}

export interface AbujaDistrict {
  key: string;
  name: string;
  region: string;
  centerX: number;
  centerY: number;
  isZonalCentre?: boolean;
}

export const ABUJA_DISTRICTS: AbujaDistrict[] = [
  { key: "all", name: "All Abuja (127 Churches)", region: "Federal Capital Territory", centerX: 600, centerY: 450 },
  { key: "jabi", name: "🏛️ Jabi (Zonal Church Group HQ)", region: "Abuja Central", centerX: 670, centerY: 465, isZonalCentre: true },
  { key: "central", name: "Central Area & CBD", region: "Abuja Central", centerX: 790, centerY: 485 },
  { key: "utako", name: "Utako & Wuye", region: "Abuja Central", centerX: 720, centerY: 480 },
  { key: "gwarinpa", name: "Gwarinpa & Dawaki", region: "Abuja North-West", centerX: 600, centerY: 340 },
  { key: "kubwa", name: "Kubwa & Byazhin", region: "Abuja North", centerX: 510, centerY: 250 },
  { key: "bwari", name: "Bwari & Ushafa", region: "Abuja North-East", centerX: 810, centerY: 160 },
  { key: "lokogoma", name: "Lokogoma, Apo & Kabusa", region: "Abuja South", centerX: 760, centerY: 620 },
  { key: "lugbe", name: "Airport Road Corridor (Lugbe)", region: "Airport Corridor", centerX: 540, centerY: 640 },
  { key: "karmo", name: "Karmo, Dape & Kado", region: "Abuja West", centerX: 610, centerY: 420 },
  { key: "gwagwalada", name: "Gwagwalada & Zuba", region: "Abuja West", centerX: 260, centerY: 600 },
  { key: "kuje", name: "Kuje & Iddo Sarki", region: "Abuja South-West", centerX: 440, centerY: 720 },
];

export const ABUJA_CHURCH_LOCATIONS: ChurchMapLocation[] = [
  {
    "id": "ch-zonal-church-1",
    "groupId": "grp-zonal-church",
    "groupName": "Zonal Church Group",
    "name": "Zonal Church 1",
    "code": "CH-ZNC1",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 660,
    "y": 451,
    "isZonalHQ": true
  },
  {
    "id": "ch-zonal-church-2",
    "groupId": "grp-zonal-church",
    "groupName": "Zonal Church Group",
    "name": "Zonal Church 2",
    "code": "CH-ZNC2",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 688,
    "y": 459,
    "isZonalHQ": true
  },
  {
    "id": "ch-lingual-church",
    "groupId": "grp-zonal-church",
    "groupName": "Zonal Church Group",
    "name": "Lingual Church",
    "code": "CH-LNG",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 652,
    "y": 475,
    "isZonalHQ": true
  },
  {
    "id": "ch-ce-city-church-zonal",
    "groupId": "grp-zonal-church",
    "groupName": "Zonal Church Group",
    "name": "CE City Church",
    "code": "CH-CCC1",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 680,
    "y": 481,
    "isZonalHQ": true
  },
  {
    "id": "ch-ce-tasha-2",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Tasha 2",
    "code": "CH-TSH2",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 790,
    "y": 485,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-fullness",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Fullness",
    "code": "CH-FLN",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 783,
    "y": 490,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-strategic-gudu",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Strategic Church Gudu",
    "code": "CH-STG",
    "districtKey": "gudu",
    "districtName": "Gudu District",
    "region": "Abuja Central",
    "x": 780,
    "y": 565,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuduru",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Kuduru",
    "code": "CH-KDR",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 830,
    "y": 140,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dawaki-3",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Dawaki 3",
    "code": "CH-DWK3",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 791,
    "y": 477,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-life-camp",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Life Camp",
    "code": "CH-LFC",
    "districtKey": "lifecamp",
    "districtName": "Life Camp",
    "region": "Abuja North-West",
    "x": 630,
    "y": 420,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-asokoro",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Asokoro",
    "code": "CH-ASK",
    "districtKey": "asokoro",
    "districtName": "Asokoro District",
    "region": "Abuja Central",
    "x": 855,
    "y": 505,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kagini-3",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Kagini 3",
    "code": "CH-KAG3",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 570,
    "y": 440,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-giri",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Giri",
    "code": "CH-GRI",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 795,
    "y": 491,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dei-dei-3",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Dei Dei 3",
    "code": "CH-DEI3",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 781,
    "y": 484,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-paipe",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Paipe",
    "code": "CH-PIP",
    "districtKey": "lugbe",
    "districtName": "Airport Road / Lugbe",
    "region": "Airport Corridor",
    "x": 550,
    "y": 630,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-cbd-2",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE CBD 2",
    "code": "CH-CBD2",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 807,
    "y": 476,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-2",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Kubwa 2",
    "code": "CH-KBW2",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 785,
    "y": 501,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kado",
    "groupId": "grp-strategic-zonal",
    "groupName": "Strategic Group Zonal",
    "name": "CE Kado",
    "code": "CH-KAD1",
    "districtKey": "kado",
    "districtName": "Kado District",
    "region": "Abuja Central",
    "x": 650,
    "y": 395,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-model-church",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Model Church",
    "code": "CH-MDC",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 720,
    "y": 450,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-utako",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Utako",
    "code": "CH-UTK1",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 713,
    "y": 455,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-excel",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Excel",
    "code": "CH-EXC",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 721,
    "y": 442,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-obansajo",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Obansajo",
    "code": "CH-OBS",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 725,
    "y": 456,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-rabah-apo",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Rabah Apo",
    "code": "CH-RBH",
    "districtKey": "apo",
    "districtName": "Apo District",
    "region": "Abuja South",
    "x": 815,
    "y": 595,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-jiwa-3",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Jiwa 3",
    "code": "CH-JW3",
    "districtKey": "jiwa",
    "districtName": "Jiwa",
    "region": "Abuja North-West",
    "x": 470,
    "y": 340,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-saburi",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Saburi",
    "code": "CH-SBR",
    "districtKey": "deidei",
    "districtName": "Dei-Dei",
    "region": "Abuja North-West",
    "x": 420,
    "y": 290,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-utako-2",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Utako 2",
    "code": "CH-UTK2",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 711,
    "y": 449,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kingship-centre",
    "groupId": "grp-heavenly-phantheon",
    "groupName": "Heavenly Phantheon Group",
    "name": "CE Kingship Centre",
    "code": "CH-KSC",
    "districtKey": "utako",
    "districtName": "Utako District",
    "region": "Abuja Central",
    "x": 737,
    "y": 441,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dawaki",
    "groupId": "grp-dawaki",
    "groupName": "Dawaki Sub-Group",
    "name": "CE Dawaki",
    "code": "CH-DWK1",
    "districtKey": "dawaki",
    "districtName": "Dawaki",
    "region": "Abuja North",
    "x": 620,
    "y": 310,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dawaki-2",
    "groupId": "grp-dawaki",
    "groupName": "Dawaki Sub-Group",
    "name": "CE Dawaki 2",
    "code": "CH-DWK2",
    "districtKey": "dawaki",
    "districtName": "Dawaki",
    "region": "Abuja North",
    "x": 613,
    "y": 315,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dawaki-5",
    "groupId": "grp-dawaki",
    "groupName": "Dawaki Sub-Group",
    "name": "CE Dawaki 5",
    "code": "CH-DWK5",
    "districtKey": "dawaki",
    "districtName": "Dawaki",
    "region": "Abuja North",
    "x": 621,
    "y": 302,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-wisdom-mopol",
    "groupId": "grp-dawaki",
    "groupName": "Dawaki Sub-Group",
    "name": "CE Wisdom Mopol Barracks",
    "code": "CH-WMP",
    "districtKey": "dawaki",
    "districtName": "Dawaki",
    "region": "Abuja North",
    "x": 625,
    "y": 316,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kbs",
    "groupId": "grp-wuye-1",
    "groupName": "Wuye Sub-Group 1",
    "name": "CE KBS",
    "code": "CH-KBS",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 725,
    "y": 510,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-lighthouse",
    "groupId": "grp-wuye-1",
    "groupName": "Wuye Sub-Group 1",
    "name": "CE Lighthouse",
    "code": "CH-LTH",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 718,
    "y": 515,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-koinonia",
    "groupId": "grp-wuye-1",
    "groupName": "Wuye Sub-Group 1",
    "name": "CE Koinonia",
    "code": "CH-KOI",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 726,
    "y": 502,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kbs-2",
    "groupId": "grp-wuye-1",
    "groupName": "Wuye Sub-Group 1",
    "name": "CE KBS 2",
    "code": "CH-KB2",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 730,
    "y": 516,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kbs-3",
    "groupId": "grp-wuye-1",
    "groupName": "Wuye Sub-Group 1",
    "name": "CE KBS 3",
    "code": "CH-KB3",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 716,
    "y": 509,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-express",
    "groupId": "grp-wuye-2",
    "groupName": "Wuye Sub-Group 2",
    "name": "CE Express",
    "code": "CH-EXP",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 742,
    "y": 501,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-livingspring",
    "groupId": "grp-wuye-2",
    "groupName": "Wuye Sub-Group 2",
    "name": "CE Livingspring",
    "code": "CH-LVS",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 720,
    "y": 526,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-pacesetters",
    "groupId": "grp-wuye-2",
    "groupName": "Wuye Sub-Group 2",
    "name": "CE Pacesetters",
    "code": "CH-PCS",
    "districtKey": "wuye",
    "districtName": "Wuye District",
    "region": "Abuja Central",
    "x": 716,
    "y": 495,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-karmo",
    "groupId": "grp-karmo",
    "groupName": "Karmo Group",
    "name": "CE Karmo",
    "code": "CH-KRM1",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 563,
    "y": 445,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dape",
    "groupId": "grp-karmo",
    "groupName": "Karmo Group",
    "name": "CE Dape",
    "code": "CH-DAP",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 571,
    "y": 432,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-karmo-2",
    "groupId": "grp-karmo",
    "groupName": "Karmo Group",
    "name": "CE Karmo 2",
    "code": "CH-KRM2",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 575,
    "y": 446,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kagini",
    "groupId": "grp-karmo",
    "groupName": "Karmo Group",
    "name": "CE Kagini",
    "code": "CH-KAG1",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 561,
    "y": 439,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwarinpa-1",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Gwarinpa 1",
    "code": "CH-GWARINPA1",
    "districtKey": "gwarinpa",
    "districtName": "Gwarinpa Estate",
    "region": "Abuja North-West",
    "x": 590,
    "y": 370,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-precious-place",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Precious Place",
    "code": "CH-PCP",
    "districtKey": "gwarinpa",
    "districtName": "Gwarinpa Estate",
    "region": "Abuja North-West",
    "x": 583,
    "y": 375,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-word-arena",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Word Arena",
    "code": "CH-WAR",
    "districtKey": "gwarinpa",
    "districtName": "Gwarinpa Estate",
    "region": "Abuja North-West",
    "x": 591,
    "y": 362,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kagini-2",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Kagini 2",
    "code": "CH-KAG2",
    "districtKey": "karmo",
    "districtName": "Karmo & Dape",
    "region": "Abuja West",
    "x": 587,
    "y": 431,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-flourish",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Flourish",
    "code": "CH-FLR",
    "districtKey": "gwarinpa",
    "districtName": "Gwarinpa Estate",
    "region": "Abuja North-West",
    "x": 595,
    "y": 376,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-karsana",
    "groupId": "grp-gwarinpa",
    "groupName": "Gwarinpa Group",
    "name": "CE Karsana",
    "code": "CH-KRS",
    "districtKey": "karsana",
    "districtName": "Karsana",
    "region": "Abuja North-West",
    "x": 560,
    "y": 335,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-solution-arena",
    "groupId": "grp-fruitful-vine",
    "groupName": "Fruitful Vine Sub-Group",
    "name": "CE Solution Arena",
    "code": "CH-SAR",
    "districtKey": "jahi",
    "districtName": "Jahi District",
    "region": "Abuja Central",
    "x": 675,
    "y": 390,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-jahi",
    "groupId": "grp-fruitful-vine",
    "groupName": "Fruitful Vine Sub-Group",
    "name": "CE Jahi",
    "code": "CH-JAH",
    "districtKey": "jahi",
    "districtName": "Jahi District",
    "region": "Abuja Central",
    "x": 668,
    "y": 395,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kado-2",
    "groupId": "grp-fruitful-vine",
    "groupName": "Fruitful Vine Sub-Group",
    "name": "CE Kado 2",
    "code": "CH-KAD2",
    "districtKey": "kado",
    "districtName": "Kado District",
    "region": "Abuja Central",
    "x": 643,
    "y": 400,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa",
    "code": "CH-KBW1",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 520,
    "y": 260,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-katampe-ext",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Katampe Ext",
    "code": "CH-KTE",
    "districtKey": "katampe",
    "districtName": "Katampe Extension",
    "region": "Abuja Central",
    "x": 730,
    "y": 375,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-3",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 3",
    "code": "CH-KBW3",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 513,
    "y": 265,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-4",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 4",
    "code": "CH-KBW4",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 521,
    "y": 252,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-5",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 5",
    "code": "CH-KBW5",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 525,
    "y": 266,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-6",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 6",
    "code": "CH-KBW6",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 511,
    "y": 259,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-8",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 8",
    "code": "CH-KBW8",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 537,
    "y": 251,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-9",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 9",
    "code": "CH-KBW9",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 515,
    "y": 276,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-10",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kubwa 10",
    "code": "CH-KBW10",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 511,
    "y": 245,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-mpape",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Mpape",
    "code": "CH-MPP",
    "districtKey": "mpape",
    "districtName": "Mpape",
    "region": "Abuja North-East",
    "x": 775,
    "y": 360,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-mabuchi",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Mabuchi",
    "code": "CH-MBC",
    "districtKey": "mabushi",
    "districtName": "Mabushi",
    "region": "Abuja Central",
    "x": 715,
    "y": 410,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kaba",
    "groupId": "grp-kubwa-1",
    "groupName": "Kubwa 1 Group",
    "name": "CE Kaba",
    "code": "CH-KAB",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 539,
    "y": 266,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kubwa-ext",
    "groupId": "grp-kubwa-2",
    "groupName": "Kubwa 2 Sub-Group",
    "name": "CE Kubwa Extension",
    "code": "CH-KBWX",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 502,
    "y": 266,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-channel-8",
    "groupId": "grp-kubwa-2",
    "groupName": "Kubwa 2 Sub-Group",
    "name": "CE Channel 8",
    "code": "CH-CH8",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 533,
    "y": 236,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-guidna",
    "groupId": "grp-kubwa-2",
    "groupName": "Kubwa 2 Sub-Group",
    "name": "CE Guidna",
    "code": "CH-GDN",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 529,
    "y": 285,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-grace-and-glory",
    "groupId": "grp-kubwa-2",
    "groupName": "Kubwa 2 Sub-Group",
    "name": "CE Grace and Glory",
    "code": "CH-GGG",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 493,
    "y": 247,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-obasanjo-road",
    "groupId": "grp-kubwa-2",
    "groupName": "Kubwa 2 Sub-Group",
    "name": "CE Obasanjo Road",
    "code": "CH-OBJ",
    "districtKey": "kubwa",
    "districtName": "Kubwa",
    "region": "Abuja North",
    "x": 550,
    "y": 254,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-bwari-main",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Bwari Main",
    "code": "CH-BWRM",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 823,
    "y": 145,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuchiko",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Kuchiko",
    "code": "CH-KCK",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 831,
    "y": 132,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-piawe",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Piawe",
    "code": "CH-PIW",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 835,
    "y": 146,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-peyi",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Peyi",
    "code": "CH-PEY",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 821,
    "y": 139,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-scc",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE SCC",
    "code": "CH-SCC",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 847,
    "y": 131,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kogo",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Kogo",
    "code": "CH-KGO",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 825,
    "y": 156,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-lambent",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Lambent",
    "code": "CH-LMB",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 821,
    "y": 125,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-garam",
    "groupId": "grp-bwari",
    "groupName": "Bwari Group",
    "name": "CE Garam",
    "code": "CH-GRM",
    "districtKey": "bwari",
    "districtName": "Bwari",
    "region": "Abuja North-East",
    "x": 849,
    "y": 146,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-ushafa",
    "groupId": "grp-new-horizon",
    "groupName": "New Horizon Group",
    "name": "CE Ushafa",
    "code": "CH-USH",
    "districtKey": "ushafa",
    "districtName": "Ushafa",
    "region": "Abuja North-East",
    "x": 780,
    "y": 200,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kogo-3",
    "groupId": "grp-new-horizon",
    "groupName": "New Horizon Group",
    "name": "CE Kogo 3",
    "code": "CH-KGO3",
    "districtKey": "ushafa",
    "districtName": "Ushafa",
    "region": "Abuja North-East",
    "x": 773,
    "y": 205,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dutse-zone-3",
    "groupId": "grp-new-horizon",
    "groupName": "New Horizon Group",
    "name": "CE Dutse Zone 3",
    "code": "CH-DTZ3",
    "districtKey": "ushafa",
    "districtName": "Ushafa",
    "region": "Abuja North-East",
    "x": 781,
    "y": 192,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dutse",
    "groupId": "grp-new-horizon",
    "groupName": "New Horizon Group",
    "name": "CE Dutse",
    "code": "CH-DTS",
    "districtKey": "ushafa",
    "districtName": "Ushafa",
    "region": "Abuja North-East",
    "x": 785,
    "y": 206,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-guto",
    "groupId": "grp-new-horizon",
    "groupName": "New Horizon Group",
    "name": "CE Guto",
    "code": "CH-GTO",
    "districtKey": "ushafa",
    "districtName": "Ushafa",
    "region": "Abuja North-East",
    "x": 771,
    "y": 199,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-1",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Gwagwalada 1",
    "code": "CH-GWG1",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 220,
    "y": 670,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-zuba",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Zuba",
    "code": "CH-ZUB",
    "districtKey": "zuba",
    "districtName": "Zuba",
    "region": "Abuja West",
    "x": 340,
    "y": 290,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-4",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Gwagwalada 4",
    "code": "CH-GWG4",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 213,
    "y": 675,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-7",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Gwagwalada 7",
    "code": "CH-GWG7",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 221,
    "y": 662,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-tunga-maje",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Tunga Maje",
    "code": "CH-TMJ",
    "districtKey": "tungamaje",
    "districtName": "Tunga Maje",
    "region": "Abuja West",
    "x": 300,
    "y": 380,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kwali",
    "groupId": "grp-gwagwalada-1",
    "groupName": "Gwagwalada 1 Group",
    "name": "CE Kwali",
    "code": "CH-KWL",
    "districtKey": "kwali",
    "districtName": "Kwali",
    "region": "Abuja South-West",
    "x": 140,
    "y": 770,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-2",
    "groupId": "grp-gwagwalada-2",
    "groupName": "Gwagwalada 2 Group",
    "name": "CE Gwagwalada 2",
    "code": "CH-GWG2",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 225,
    "y": 676,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-3",
    "groupId": "grp-gwagwalada-2",
    "groupName": "Gwagwalada 2 Group",
    "name": "CE Gwagwalada 3",
    "code": "CH-GWG3",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 211,
    "y": 669,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-anagada",
    "groupId": "grp-gwagwalada-2",
    "groupName": "Gwagwalada 2 Group",
    "name": "CE Anangada",
    "code": "CH-ANG",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 237,
    "y": 661,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gwagwalada-6",
    "groupId": "grp-gwagwalada-2",
    "groupName": "Gwagwalada 2 Group",
    "name": "CE Gwagwalada 6",
    "code": "CH-GWG6",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 215,
    "y": 686,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-chukunku",
    "groupId": "grp-gwagwalada-2",
    "groupName": "Gwagwalada 2 Group",
    "name": "CE Chukunku",
    "code": "CH-CHK",
    "districtKey": "gwagwalada",
    "districtName": "Gwagwalada",
    "region": "Abuja West",
    "x": 211,
    "y": 655,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje",
    "code": "CH-KUJ1",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 430,
    "y": 740,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-2",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 2",
    "code": "CH-KUJ2",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 423,
    "y": 745,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-3",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 3",
    "code": "CH-KUJ3",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 431,
    "y": 732,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-4",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 4",
    "code": "CH-KUJ4",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 435,
    "y": 746,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-5",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 5",
    "code": "CH-KUJ5",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 421,
    "y": 739,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-iddo-sarki",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Iddo Sarki",
    "code": "CH-IDS",
    "districtKey": "iddosarki",
    "districtName": "Iddo Sarki",
    "region": "Airport Corridor",
    "x": 480,
    "y": 660,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-6",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 6",
    "code": "CH-KUJ6",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 447,
    "y": 731,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-7",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 7",
    "code": "CH-KUJ7",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 425,
    "y": 756,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kuje-8",
    "groupId": "grp-kuje",
    "groupName": "Kuje Group",
    "name": "CE Kuje 8",
    "code": "CH-KUJ8",
    "districtKey": "kuje",
    "districtName": "Kuje",
    "region": "Abuja South-West",
    "x": 421,
    "y": 725,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-lokogoma",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Lokogoma",
    "code": "CH-LKG1",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 720,
    "y": 620,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kabusa",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Kabusa",
    "code": "CH-KABUSA",
    "districtKey": "kabusa",
    "districtName": "Kabusa",
    "region": "Abuja South",
    "x": 730,
    "y": 670,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-durumi",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Durumi",
    "code": "CH-DRM",
    "districtKey": "durumi",
    "districtName": "Durumi",
    "region": "Abuja South",
    "x": 735,
    "y": 560,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-apo",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Apo",
    "code": "CH-APO1",
    "districtKey": "apo",
    "districtName": "Apo District",
    "region": "Abuja South",
    "x": 808,
    "y": 600,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-apo-dutse",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Apo Dutse",
    "code": "CH-APD",
    "districtKey": "apo",
    "districtName": "Apo District",
    "region": "Abuja South",
    "x": 816,
    "y": 587,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-wumba",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Wumba",
    "code": "CH-WMB",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 713,
    "y": 625,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-gbuduwyi",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Gbuduwyi",
    "code": "CH-GBD",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 721,
    "y": 612,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-damagaza",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Damagaza",
    "code": "CH-DMG",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 725,
    "y": 626,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-pigbakasa",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Pigbakasa",
    "code": "CH-PBK",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 711,
    "y": 619,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-city-of-david",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE City of David",
    "code": "CH-COD",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 737,
    "y": 611,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-citadel-of-grace",
    "groupId": "grp-lokogoma",
    "groupName": "Lokogoma Group",
    "name": "CE Citadel of Grace",
    "code": "CH-COG",
    "districtKey": "lokogoma",
    "districtName": "Lokogoma",
    "region": "Abuja South",
    "x": 715,
    "y": 636,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-deidei-2",
    "groupId": "grp-dei-dei",
    "groupName": "Dei Dei Group",
    "name": "CE Deidei 2",
    "code": "CH-DEI2",
    "districtKey": "deidei",
    "districtName": "Dei-Dei",
    "region": "Abuja North-West",
    "x": 413,
    "y": 295,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-airport-road",
    "groupId": "grp-airport-road",
    "groupName": "Airport Road Sub-Group",
    "name": "CE Airport Road",
    "code": "CH-APR1",
    "districtKey": "lugbe",
    "districtName": "Airport Road / Lugbe",
    "region": "Airport Corridor",
    "x": 543,
    "y": 635,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-airport-road-2",
    "groupId": "grp-airport-road",
    "groupName": "Airport Road Sub-Group",
    "name": "CE Airport Road 2",
    "code": "CH-APR2",
    "districtKey": "lugbe",
    "districtName": "Airport Road / Lugbe",
    "region": "Airport Corridor",
    "x": 551,
    "y": 622,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-airport-road-4",
    "groupId": "grp-airport-road",
    "groupName": "Airport Road Sub-Group",
    "name": "CE Airport Road 4",
    "code": "CH-APR4",
    "districtKey": "lugbe",
    "districtName": "Airport Road / Lugbe",
    "region": "Airport Corridor",
    "x": 555,
    "y": 636,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-kapwa",
    "groupId": "grp-airport-road",
    "groupName": "Airport Road Sub-Group",
    "name": "CE Kapwa",
    "code": "CH-KPW",
    "districtKey": "lugbe",
    "districtName": "Airport Road / Lugbe",
    "region": "Airport Corridor",
    "x": 541,
    "y": 629,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-dutse-makaranta",
    "groupId": "grp-dutse-makaranta",
    "groupName": "Dutse Makaranta Sub-Group",
    "name": "CE Dutse Makaranta",
    "code": "CH-DMK1",
    "districtKey": "dutse",
    "districtName": "Dutse Makaranta",
    "region": "Abuja North",
    "x": 650,
    "y": 275,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-garki-1",
    "groupId": "grp-dutse-makaranta",
    "groupName": "Dutse Makaranta Sub-Group",
    "name": "CE Garki 1",
    "code": "CH-GRK1",
    "districtKey": "garki",
    "districtName": "Garki District",
    "region": "Abuja Central",
    "x": 795,
    "y": 545,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-springtime",
    "groupId": "grp-dutse-makaranta",
    "groupName": "Dutse Makaranta Sub-Group",
    "name": "CE Springtime",
    "code": "CH-SPT",
    "districtKey": "dutse",
    "districtName": "Dutse Makaranta",
    "region": "Abuja North",
    "x": 643,
    "y": 280,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-new-jerusalem",
    "groupId": "grp-dutse-makaranta",
    "groupName": "Dutse Makaranta Sub-Group",
    "name": "CE New Jerusalem",
    "code": "CH-NJR",
    "districtKey": "dutse",
    "districtName": "Dutse Makaranta",
    "region": "Abuja North",
    "x": 651,
    "y": 267,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-mbuko",
    "groupId": "grp-dutse-makaranta",
    "groupName": "Dutse Makaranta Sub-Group",
    "name": "CE Mbuko",
    "code": "CH-MBK",
    "districtKey": "dutse",
    "districtName": "Dutse Makaranta",
    "region": "Abuja North",
    "x": 655,
    "y": 281,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-city-church",
    "groupId": "grp-city-church",
    "groupName": "CE Abuja City Church",
    "name": "CE City Church",
    "code": "CH-CCC",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 661,
    "y": 464,
    "isZonalHQ": false
  },
  {
    "id": "ch-teens-church",
    "groupId": "grp-teens-church",
    "groupName": "Teens Church Group",
    "name": "Teens Church",
    "code": "CH-TCG",
    "districtKey": "jabi",
    "districtName": "Jabi District",
    "region": "Abuja Central",
    "x": 687,
    "y": 456,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-byazhin",
    "groupId": "grp-byazhin",
    "groupName": "Byazhin Church",
    "name": "CE Byazhin",
    "code": "CH-BYZ",
    "districtKey": "byazhin",
    "districtName": "Byazhin",
    "region": "Abuja North",
    "x": 480,
    "y": 235,
    "isZonalHQ": false
  },
  {
    "id": "ch-ce-wealthy-place",
    "groupId": "grp-wealthy-place",
    "groupName": "Wealthy Place Church",
    "name": "CE Wealthy Place",
    "code": "CH-WLP",
    "districtKey": "cbd",
    "districtName": "Central Business District",
    "region": "Abuja Central",
    "x": 781,
    "y": 470,
    "isZonalHQ": false
  }
];
